# Generated by Django 4.0.4 on 2022-04-13 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Tank name', max_length=50, unique=True, verbose_name='Tank name')),
                ('types', models.CharField(choices=[('Heavy', 'Heavy'), ('Medium', 'Medium'), ('Light', 'Light'), ('Destroyer', 'Destroyer'), ('Arty', 'Arty')], max_length=50, verbose_name='Type of tank')),
                ('tank_class', models.CharField(choices=[('U.S.A.', 'U.S.A.'), ('GERMANY', 'GERMANY'), ('U.K.', 'U.K.'), ('U.S.S.R.', 'U.S.S.R.'), ('FRANCE', 'FRANCE'), ('JAPAN', 'JAPAN'), ('CHINA', 'CHINA'), ('CZECHOSLOVAKIA', 'CZECHOSLOVAKIA'), ('SWEDEN', 'SWEDEN'), ('POLAND', 'POLAND'), ('ITALY', 'ITALY')], max_length=50, verbose_name='Choose nation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Tank type', max_length=50, unique=True, verbose_name='Tank type')),
                ('abbr', models.CharField(help_text='Enter Abbreviation', max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Taml tyúe Abbreviation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
