# Generated by Django 4.0.4 on 2022-05-30 18:53

from django.db import migrations, models
import myfirst.models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myfirst.models.img_path, verbose_name='Image'),
        ),
    ]
