# Generated by Django 4.0.4 on 2022-05-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0002_attachment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='abbr',
        ),
    ]
